# --- NORD DARK CORE ---
foreground              #DBDBDB
background              #131517
selection_foreground    #131517
selection_background    #70949E

cursor                  #DBDBDB
cursor_text_color       #131517

url_color               #8BA0B6


# --- BORDERS / TABS ---
active_border_color     #70949E
inactive_border_color   #1A1B1D
bell_border_color       #E7CC98

active_tab_foreground   #131517
active_tab_background   #70949E
inactive_tab_foreground #A2A2A2
inactive_tab_background #1A1B1D
tab_bar_background      #131517


# --- ANSI COLORS (NORD DARK) ---
# Preto / fundo
color0  #131517
color8  #3A3F44

# Vermelho (erro)
color1  #974B53
color9  #B6676D

# Verde (string / sucesso)
color2  #A8BC96
color10 #C1D4AF

# Amarelo (warning)
color3  #E7CC98
color11 #F0DDB1

# Azul (keywords)
color4  #8BA0B6
color12 #A6BBD3

# Roxo (funções)
color5  #B79CB2
color13 #D0B6CB

# Ciano (accent)
color6  #70949E
color14 #8FB3BD

# Branco / texto
color7  #DBDBDB
color15 #FFFFFF
