exec-once = waybar
exec-once = swww-daemon
exec-once = hypridle
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ./scripts/spotify_notify.sh


# exec-once = sleep 3 && linux-wallpaperengine --screen-root eDP-1 --bg 3289988463
# exec-once = sleep 3 && linux-wallpaperengine --screen-root HDMI-A-1 --bg 3289988463