source = ./configs/autostart.conf
source = ./configs/environment.conf
source = ./configs/input.conf
source = ./configs/keybinds.conf
source = ./configs/monitors.conf
source = ./configs/windowsrules.conf
source = ./configs/workspaces.conf
source = ./configs/general.conf
source = ./configs/decoration.conf
source = ./configs/animations.conf
source = ./configs/layouts.conf
source = ./configs/misc.conf
