input {
    kb_layout = br
    kb_variant = abnt2
    kb_model =
    kb_options =
    kb_rules =
    repeat_delay = 200
    repeat_rate = 60

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = 0.5
}
