# Programs vars
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = brave
$browserSsp = google-chrome-stable
$code = code
$code2 = antigravity
$dc = discord
$spotify = spotify

# Super = Windows Key
$mainMod = SUPER

# Custom keybinds
bind = $mainMod, ç, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, t, exec, $terminal
bind = $mainMod, W, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Q, togglefloating,
bind = $mainMod, space, exec, $menu
bind = $mainMod, J, togglesplit,
bind = $mainMod, B, exec, $browser
bind = $mainMod, N, exec, $browserSsp
bind = $mainMod, C, exec, $code
bind = $mainMod, G, exec, $code2
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen
bind = , Print, exec, grimblast --notify --freeze copysave area ~/Pictures/Screenshots/%Y-%m-%d_%H-%M-%S.png
bind = $mainMod, R, exec, sh -c "pkill waybar; waybar &"
bind = $mainMod SHIFT, C, exec, hyprpicker -a
bind = $mainMod, D, exec, $dc
bind = $mainMod, Z, exec, $spotify
bind = $mainMod, escape, exec, bash ~/.config/hypr/scripts/toggle_waybar.sh
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, P, exec, wlogout

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
