windowrule = match:class .*, suppress_event maximize

windowrule = match:class ^()$, match:title ^()$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

windowrule = match:class ^(hyprland-run)$, float on
windowrule = match:class ^(hyprland-run)$, move 20 (monitor_h-120)

windowrule = match:class .*, opacity 0.98 0.90
windowrule = match:class ^([Bb]rave.*)$, opacity 1.0
windowrule = match:class ^(google-chrome)$, opacity 1.0
windowrule = match:class ^(kitty)$, opacity 0.92 0.88

windowrule = match:title ^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload)(.*)$, float on
windowrule = match:title ^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload)(.*)$, center on
windowrule = match:title ^(Save As|Save a File|Pick Files|Open File|Open Files)$, float on
windowrule = match:title ^(Save As|Save a File|Pick Files|Open File|Open Files)$, size 50% 60%
windowrule = match:title ^(Save As|Save a File|Pick Files|Open File|Open Files)$, center on

windowrule = match:class ^(pavucontrol|nm-connection-editor|blueberry\.py)$, float on
windowrule = match:class ^(pavucontrol|nm-connection-editor)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(pavucontrol|nm-connection-editor)$, center on

windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, pin on

windowrule = match:title .*\.exe, immediate on
windowrule = match:class ^(steam_app).*, immediate on

layerrule = match:namespace logout_dialog, blur on
layerrule = match:namespace logout_dialog, ignore_alpha 0.15
layerrule = match:namespace logout_dialog, no_anim on

layerrule = match:namespace dunst, blur on
layerrule = match:namespace dunst, ignore_alpha 0.15
