general {
    gaps_in = 3
    gaps_out = 6

    border_size = 2

    col.active_border = rgba(70949eff) rgba(466973ee) 45deg
    # col.active_border = rgba(dbdbdbff) rgba(d1d1d1ff) 45deg
    col.inactive_border = rgba(1A1B1Dcc)


    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 8
    rounding_power = 2

    shadow {
        enabled = true
        range = 25
        render_power = 2
        color = rgba(00000034)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        vibrancy = 0.2
        noise = 0.0117
        contrast = 0.97
        brightness = 1
        xray = false
        new_optimizations = true
    }
}
