# Programs vars
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = brave
$code = code

# Super = Windows Key
$mainMod = SUPER

# Custom keybinds
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, P, exec, wlogout
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, T, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Space, exec, $menu
bind = $mainMod, W, killactive,
bind = $mainMod, Q, togglefloating
bind = $mainMod, B, exec, $browser
bind = $mainMod, C, exec, $code
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen
# bind = , Print, exec, ~/.config/hypr/scripts/screenshot.sh
bind = , Print, exec, ~/.config/hypr/scripts/screenshot-freeze.sh
bind = $mainMod, R, exec, ~/.config/hypr/scripts/reload-waybar.sh
bind = $mainMod SHIFT, C, exec, hyprpicker -a
bind = $mainMod, escape, exec, ~/.config/hypr/scripts/toggle-waybar.sh

# Laptop multimedia keys for volume and LCD brightness
bindel = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/volume.sh --inc
bindel = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume.sh --dec
bindel = , XF86AudioMute, exec, ~/.config/hypr/scripts/volume.sh --toggle
# bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness.sh --inc
bindel = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness.sh --dec

# Requires playerctl
# bindl = , XF86AudioNext, exec, playerctl next
# bindl = , XF86AudioPause, exec, playerctl play-pause
# bindl = , XF86AudioPlay, exec, playerctl play-pause
# bindl = , XF86AudioPrev, exec, playerctl previous
