# Super = Windows Key
$mainMod = SUPER

# 2nd monitor always on workspace 10
workspace = 10, monitor:HDMI-A-1, default:true, persistent:true

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, X, workspace, 10

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, X, movetoworkspace, 10

# Example special workspace
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Move/resize windows
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Trocar janela ativa com a da esquerda/direita/cima/baixo
bind = $mainMod, left, swapwindow, l
bind = $mainMod, right, swapwindow, r
bind = $mainMod, up, swapwindow, u
bind = $mainMod, down, swapwindow, d

# Move focus
# bind = $mainMod SHIFT, left, movefocus, l
# bind = $mainMod SHIFT, right, movefocus, r
# bind = $mainMod SHIFT, up, movefocus, u
# bind = $mainMod SHIFT, down, movefocus, d